// import type { Metadata } from "next";
import { Red_Hat_Text } from "next/font/google";
// import { NavBar } from "@/components";

// const red_hat_text = Red_Hat_Text({
//   subsets: ["latin"],
//   weight: ["400", "600", "700"],
// });

// export const metadata: Metadata = {
//   title: "E-commerce App",
//   description: "Generated by me",
// };

import './globals.css';


import { SessionProvider } from "next-auth/react";
import { NavBar } from "@/components";
export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
        <SessionProvider session={session}>
          <div className="w-11/12 mx-auto">
          <NavBar />
          {<Component {...pageProps} />}
          </div>
        </SessionProvider>
      
  );
}
